# Generated by Django 6.1.1 on 2026-09-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('inn', models.CharField(max_length=200)),
                ('ogrn', models.CharField(blank=True, max_length=200)),
                ('kpp', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(max_length=200)),
                ('contacts', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.FileField(upload_to='documents/')),
                ('file_hash', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('document_type', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_code', models.CharField(max_length=200)),
                ('ks2_position', models.CharField(max_length=200)),
                ('estimated_volume', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Сметная строка',
                'verbose_name_plural': 'Сметные строки',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=200)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве')], default='active', max_length=20)),
                ('reference_link', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Стандарт',
                'verbose_name_plural': 'Стандарты',
            },
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('construction_start', models.DateField()),
                ('planned_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sites', to='core.counterparty')),
                ('general_contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_sites', to='core.counterparty')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('acceptance_status', models.CharField(choices=[('accepted', 'принята'), ('accepted with remarks', 'принята с замечаниями'), ('rejected', 'отклонена')], max_length=100)),
                ('has_quality_passport', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.constructionsite')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.counterparty')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('matching_status', models.CharField(choices=[('unidentified', 'не опознано'), ('auto identified', 'автоматически опознано'), ('confirmed', 'подтверждено')], default='unidentified', max_length=30)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.deliverynote')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставки',
            },
        ),
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=200)),
                ('estimate_code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('order_number', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве')], default='active', max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.constructionsite')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.standard')),
            ],
            options={
                'verbose_name': 'Раздел документации',
                'verbose_name_plural': 'Разделы документации',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('auto identified', 'автоматически опознано'), ('confirmed', 'подтверждено'), ('rejected', 'отклонена')], default='auto identified', max_length=30)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.counterparty')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.documents')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='HiddenWorkAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=200)),
                ('drawn_up_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На подписании'), ('ACCEPTED', 'Подписан'), ('REJECTED', 'Отклонен')], default='DRAFT', max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documentationsection')),
            ],
            options={
                'verbose_name': 'Акт ОСР',
                'verbose_name_plural': 'Акты ОСР',
            },
        ),
        migrations.CreateModel(
            name='ActMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_off_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.deliveryitem')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hiddenworkact')),
            ],
            options={
                'verbose_name': 'Использованные материалы в акте',
            },
        ),
        migrations.CreateModel(
            name='ActAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documents')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hiddenworkact')),
            ],
            options={
                'verbose_name': 'Приложение к акту',
                'verbose_name_plural': 'Приложение к акту',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве')], default='active', max_length=20)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.counterparty')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.standard')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.material'),
        ),
        migrations.CreateModel(
            name='MaterialCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.certificate')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
            ],
            options={
                'verbose_name': 'Сертификат материала',
                'verbose_name_plural': 'Сертификаты материалов',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('order_document', models.CharField(blank=True, max_length=200)),
                ('authority_end_date', models.DateField(blank=True, null=True)),
                ('nrs_id', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве')], default='active', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.counterparty')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='IncomingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspection_result', models.CharField(max_length=200)),
                ('usage_permission', models.BooleanField()),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.deliveryitem')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'verbose_name': 'Входной контроль',
            },
        ),
        migrations.CreateModel(
            name='DeviationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('decision_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'На подписании'), ('ACCEPTED', 'Согласовано'), ('REJECTED', 'Отклонен')], default='PENDING', max_length=200)),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.documents')),
                ('estimate_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estimateline')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'verbose_name': 'Решение по отклонению',
                'verbose_name_plural': 'Решения по отклонениям',
            },
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person'),
        ),
        migrations.CreateModel(
            name='ActSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_act', models.CharField(max_length=200)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hiddenworkact')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'verbose_name': 'Подписант акта',
                'verbose_name_plural': 'Подписанты акта',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('building', models.CharField(blank=True, max_length=40)),
                ('explication_name', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.constructionsite')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.AddField(
            model_name='estimateline',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.room'),
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=10)),
                ('requires_hidden_work_act', models.BooleanField()),
                ('allowed_deviation_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_number', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве')], default='active', max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documentationsection')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.standard')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работы',
            },
        ),
        migrations.AddField(
            model_name='estimateline',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.worktype'),
        ),
        migrations.CreateModel(
            name='WorkVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_date', models.DateField()),
                ('actual_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('acceptance_status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На подписании'), ('ACCEPTED', 'Подписан'), ('REJECTED', 'Отклонен')], default='DRAFT', max_length=20)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hiddenworkact')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.room')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.worktype')),
            ],
            options={
                'verbose_name': 'Объем работы',
                'verbose_name_plural': 'Объемы работ',
            },
        ),
    ]
